# version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/facebook
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=facebook.settings
    depends_on:
      - redis

  redis:
    image: redis:alpine
