# Generated by Django 5.0.1 on 2024-08-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0004_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='chat_type',
            field=models.CharField(choices=[('private', 'Private'), ('group', 'Group')], default='group', max_length=200),
        ),
        migrations.AddField(
            model_name='messages',
            name='room_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
