# Generated by Django 5.0.1 on 2024-09-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0008_alter_messages_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
