# Generated by Django 5.0.1 on 2024-09-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0010_messages_file_messages_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
