# Generated by Django 5.0.1 on 2024-09-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0011_alter_messages_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
