# Generated by Django 5.0.1 on 2024-09-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0012_messages_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='vedio',
            field=models.FileField(blank=True, null=True, upload_to='vedio/'),
        ),
    ]
