# Generated by Django 5.0.1 on 2024-09-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0013_messages_vedio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='vedio',
        ),
        migrations.AddField(
            model_name='messages',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
    ]
