# Generated by Django 5.0.1 on 2024-01-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting_blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='is_deleted',
            field=models.BooleanField(default=True),
        ),
    ]
